#!/usr/bin/env bash
set -euo pipefail

JOIN_FILE="/vagrant/join-command.sh"

for _ in $(seq 1 60); do
  if [ -s "${JOIN_FILE}" ]; then
    break
  fi
  sleep 10
done

if [ ! -s "${JOIN_FILE}" ]; then
  echo "Join command was not generated by master."
  exit 1
fi

if [ ! -f /etc/kubernetes/kubelet.conf ]; then
  sudo bash "${JOIN_FILE}"
fi
